#!/usr/bin/env python3
"""Create a new Alembic revision under ``alembic/versions/``.

Autogenerated revisions **must be reviewed** before commit: they can miss renames,
drop columns unintentionally, or diverge from the intended research schema.

Examples::

    python scripts/db_revision.py "add foo column"
    python scripts/db_revision.py "align with schema" --autogenerate

``--autogenerate`` requires ``DATABASE_URL`` so Alembic can reflect the live database.
"""

from __future__ import annotations

import argparse
import os
import sys
from pathlib import Path

_ROOT = Path(__file__).resolve().parent.parent


def main() -> int:
    from alembic import command
    from alembic.config import Config

    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("message", help="Short description for the revision slug")
    parser.add_argument(
        "--autogenerate",
        action="store_true",
        help="Compare ORM metadata to the database (requires DATABASE_URL)",
    )
    args = parser.parse_args()

    ini = _ROOT / "alembic.ini"
    if not ini.is_file():
        print("error: alembic.ini not found", file=sys.stderr)
        return 1

    if args.autogenerate:
        from kalshi_no_carry.config import get_settings

        settings = get_settings()
        if not settings.database_url:
            print("error: DATABASE_URL is required for --autogenerate", file=sys.stderr)
            return 1
        os.environ["DATABASE_URL"] = str(settings.database_url)

    cfg = Config(str(ini))
    try:
        command.revision(cfg, message=args.message, autogenerate=args.autogenerate)
    except Exception as exc:
        print(f"error: alembic revision failed ({type(exc).__name__})", file=sys.stderr)
        return 1

    print(
        "ok: revision created under alembic/versions/ — review the file before committing."
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
